apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-cluster 
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc 
  project: default
  source:
    path: clusters/prod-cluster/apps
    repoURL: https://github.com/roger-beathard/argocd-test/
    targetRevision: HEAD
#  syncPolicy:
#    syncOptions:
#    - CreateNamespace=true
#    automated:
#      selfHeal: true
#      prune: true
